/*
 * Offline generator: prints a C initializer for REG_CANDIDATES in regalloc.c
 * by running ccf_enumerate_templates() and converting CCFTemplate -> RegCandidate.
 *
 * Build (from repo root):
 *   cc -std=c17 -O2 -Iinclude tools/gen_reg_candidates.c src/ccf.c src/cube.c \
 *      src/util.c -o tools/gen_reg_candidates
 *
 * Run (from repo root):
 *   tools/gen_reg_candidates
 */
#include "../include/ccf.h"
#include "../include/cube.h"

#include <stdio.h>
#include <stdlib.h>

int main(void) {
    cube_init();

    CCFTemplate templates[2000];
    int n = ccf_enumerate_templates(templates, 2000);

    printf("/* Auto-generated by tools/gen_reg_candidates — do not edit by hand.\n");
    printf(" * Each entry: { order, num_cycles, { {orbit,length,net_ori}, ... } }\n");
    printf(" * orbit: 0=corners, 1=edges\n");
    printf(" * Sorted by order ASC, then total pieces ASC (most compact first). */\n");
    printf("static const RegCandidate REG_CANDIDATES[] = {\n");

    for (int i = 0; i < n; i++) {
        const CCFTemplate *t = &templates[i];
        int total = t->corner_cost + t->edge_cost;
        printf("    {%3d, %d, {", t->order, t->num_cycles);
        for (int c = 0; c < t->num_cycles; c++) {
            const CCFCycle *cy = &t->cycles[c];
            printf("{%d,%d,%d}", cy->orbit, cy->length, cy->net_orientation);
            if (c + 1 < t->num_cycles) printf(", ");
        }
        /* pad to 4 cycle slots so the closing braces line up */
        for (int c = t->num_cycles; c < 4; c++) {
            printf(", {0,0,0}");
        }
        printf("}},  /* order=%d pieces=%d */\n", t->order, total);
    }

    printf("};\n");
    printf("/* %d templates total */\n", n);
    return 0;
}
