#include "../include/regalloc.h"
#include "../include/alg.h"
#include "../include/ccs.h"
#include "../include/interference.h"
#include "../include/piece.h"
#include "../include/util.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* IDA* is only a fallback when no Kociemba CCS template fits. Its cost grows
 * ~13^depth, so this stays modest: deep enough to beat the original depth 6,
 * shallow enough that an infeasible request fails in seconds rather than
 * minutes. The order-aware leaf filter (see idas_dfs) is what actually lets a
 * shorter ceiling still find useful high-order registers. */
#ifndef REGALLOC_IDA_MAX_DEPTH
#define REGALLOC_IDA_MAX_DEPTH 7
#endif

#ifndef REGALLOC_CACHE_PATH
#define REGALLOC_CACHE_PATH "regalloc-registers.bin"
#endif

#define MOVE_COUNT 18

/* --- IDA* constants ---
 * All 18 moves in fixed canonical order: UDLRFB, q=1,2,3.
 */

static const Move ALL_MOVES[MOVE_COUNT] = {
    {FACE_U, 1}, {FACE_U, 2}, {FACE_U, 3},
    {FACE_D, 1}, {FACE_D, 2}, {FACE_D, 3},
    {FACE_L, 1}, {FACE_L, 2}, {FACE_L, 3},
    {FACE_R, 1}, {FACE_R, 2}, {FACE_R, 3},
    {FACE_F, 1}, {FACE_F, 2}, {FACE_F, 3},
    {FACE_B, 1}, {FACE_B, 2}, {FACE_B, 3},
};

static const PieceLabel CORNER_PIECES[] = {
    PC_UFL, PC_UFR, PC_UBL, PC_UBR, PC_DFL, PC_DFR, PC_DBL, PC_DBR,
};

static const PieceLabel EDGE_PIECES[] = {
    PC_UF, PC_UB, PC_UL, PC_UR, PC_DF, PC_DB, PC_DL, PC_DR,
    PC_FL, PC_FR, PC_BL, PC_BR,
};

#define REG_CANDIDATE_MAX_CYCLES 5

typedef struct {
    uint8_t orbit;           /* 0 = corners, 1 = edges */
    uint8_t length;
    int8_t  net_orientation;
} RegCycleCandidate;

typedef struct {
    int order;
    int num_cycles;
    RegCycleCandidate cycles[REG_CANDIDATE_MAX_CYCLES];
} RegCandidate;

/* Auto-generated by tools/gen_reg_candidates. One entry per achievable order,
 * cheapest (fewest pieces) realisation first. Sorted order-ASC so that
 * ccs_find_small_register naturally tries the most compact option that
 * satisfies required_order before falling back to higher orders. */
static const RegCandidate REG_CANDIDATES[] = {
    {   2, 2, {{1,1,1}, {1,1,1}} },                          /* pieces=2  */
    {   3, 2, {{0,1,1}, {0,1,2}} },                          /* pieces=2  */
    {   4, 2, {{1,2,1}, {1,2,1}} },                          /* pieces=4  */
    {   5, 1, {{0,5,0}} },                                   /* pieces=5  */
    {   6, 2, {{0,2,1}, {0,2,2}} },                          /* pieces=4  */
    {   7, 1, {{0,7,0}} },                                   /* pieces=7  */
    {   8, 2, {{1,2,1}, {1,4,1}} },                          /* pieces=6  */
    {   9, 2, {{0,1,1}, {0,3,2}} },                          /* pieces=4  */
    {  10, 2, {{1,1,1}, {1,5,1}} },                          /* pieces=6  */
    {  11, 1, {{1,11,0}} },                                  /* pieces=11 */
    {  12, 2, {{0,2,1}, {0,4,2}} },                          /* pieces=6  */
    {  14, 2, {{1,1,1}, {1,7,1}} },                          /* pieces=8  */
    {  15, 2, {{0,1,1}, {0,5,2}} },                          /* pieces=6  */
    {  16, 2, {{1,2,1}, {1,8,1}} },                          /* pieces=10 */
    {  18, 4, {{0,1,1}, {0,3,2}, {1,1,1}, {1,1,1}} },       /* pieces=6  */
    {  20, 3, {{0,2,0}, {1,2,1}, {1,5,1}} },                 /* pieces=9  */
    {  21, 2, {{0,1,1}, {0,7,2}} },                          /* pieces=8  */
    {  22, 2, {{1,1,1}, {1,11,1}} },                         /* pieces=12 */
    {  24, 4, {{0,1,1}, {0,1,2}, {1,2,1}, {1,4,1}} },       /* pieces=8  */
    {  28, 3, {{0,2,0}, {1,2,1}, {1,7,1}} },                 /* pieces=11 */
    {  30, 2, {{1,3,1}, {1,5,1}} },                          /* pieces=8  */
    {  33, 3, {{0,1,1}, {0,1,2}, {1,11,0}} },                /* pieces=13 */
    {  35, 2, {{0,5,0}, {1,7,0}} },                          /* pieces=12 */
    {  36, 4, {{0,1,1}, {0,3,2}, {1,2,1}, {1,2,1}} },       /* pieces=8  */
    {  40, 3, {{0,2,0}, {1,4,1}, {1,5,1}} },                 /* pieces=11 */
    {  42, 2, {{1,3,1}, {1,7,1}} },                          /* pieces=10 */
    {  44, 3, {{0,2,0}, {0,4,0}, {1,11,0}} },                /* pieces=17 */
    {  45, 2, {{0,3,1}, {0,5,2}} },                          /* pieces=8  */
    {  48, 4, {{0,1,1}, {0,1,2}, {1,2,1}, {1,8,1}} },       /* pieces=12 */
    {  55, 2, {{0,5,0}, {1,11,0}} },                         /* pieces=16 */
    {  56, 3, {{0,2,0}, {1,4,1}, {1,7,1}} },                 /* pieces=13 */
    {  60, 4, {{0,1,1}, {0,2,2}, {1,2,1}, {1,5,1}} },       /* pieces=10 */
    {  63, 3, {{0,1,1}, {0,3,2}, {1,7,0}} },                 /* pieces=11 */
    {  66, 4, {{0,1,1}, {0,1,2}, {1,1,1}, {1,11,1}} },      /* pieces=14 */
    {  70, 2, {{1,5,1}, {1,7,1}} },                          /* pieces=12 */
    {  72, 4, {{0,1,1}, {0,3,2}, {1,2,1}, {1,4,1}} },       /* pieces=10 */
    {  77, 2, {{0,7,0}, {1,11,0}} },                         /* pieces=18 */
    {  80, 3, {{0,5,0}, {1,2,1}, {1,8,1}} },                 /* pieces=15 */
    {  84, 4, {{0,1,1}, {0,2,2}, {1,2,1}, {1,7,1}} },       /* pieces=12 */
    {  90, 4, {{0,1,1}, {0,3,2}, {1,1,1}, {1,5,1}} },       /* pieces=10 */
    {  99, 3, {{0,1,1}, {0,3,2}, {1,11,0}} },                /* pieces=15 */
    { 105, 3, {{0,1,1}, {0,5,2}, {1,7,0}} },                 /* pieces=13 */
    { 110, 3, {{0,5,0}, {1,1,1}, {1,11,1}} },                /* pieces=17 */
    { 112, 3, {{0,7,0}, {1,2,1}, {1,8,1}} },                 /* pieces=17 */
    { 120, 4, {{0,1,1}, {0,2,2}, {1,4,1}, {1,5,1}} },       /* pieces=12 */
    { 126, 4, {{0,1,1}, {0,3,2}, {1,1,1}, {1,7,1}} },       /* pieces=12 */
    { 132, 3, {{0,2,1}, {0,4,2}, {1,11,0}} },                /* pieces=17 */
    { 140, 4, {{0,2,0}, {0,5,0}, {1,2,1}, {1,7,1}} },       /* pieces=16 */
    { 144, 4, {{0,1,1}, {0,3,2}, {1,2,1}, {1,8,1}} },       /* pieces=14 */
    { 154, 3, {{0,7,0}, {1,1,1}, {1,11,1}} },                /* pieces=19 */
    { 165, 3, {{0,1,1}, {0,5,2}, {1,11,0}} },                /* pieces=17 */
    { 168, 4, {{0,1,1}, {0,2,2}, {1,4,1}, {1,7,1}} },       /* pieces=14 */
    { 180, 4, {{0,2,1}, {0,3,2}, {1,2,1}, {1,5,1}} },       /* pieces=12 */
    { 198, 4, {{0,1,1}, {0,3,2}, {1,1,1}, {1,11,1}} },      /* pieces=16 */
    { 210, 4, {{0,1,1}, {0,1,2}, {1,5,1}, {1,7,1}} },       /* pieces=14 */
    { 231, 3, {{0,1,1}, {0,7,2}, {1,11,0}} },                /* pieces=19 */
    { 240, 4, {{0,1,1}, {0,5,2}, {1,2,1}, {1,8,1}} },       /* pieces=16 */
    { 252, 4, {{0,2,1}, {0,3,2}, {1,2,1}, {1,7,1}} },       /* pieces=14 */
    { 280, 4, {{0,2,0}, {0,5,0}, {1,4,1}, {1,7,1}} },       /* pieces=18 */
    { 315, 3, {{0,3,1}, {0,5,2}, {1,7,0}} },                 /* pieces=15 */
    { 330, 4, {{0,1,1}, {0,5,2}, {1,1,1}, {1,11,1}} },      /* pieces=18 */
    { 336, 4, {{0,1,1}, {0,7,2}, {1,2,1}, {1,8,1}} },       /* pieces=18 */
    { 360, 4, {{0,2,1}, {0,3,2}, {1,4,1}, {1,5,1}} },       /* pieces=14 */
    { 420, 4, {{0,2,1}, {0,5,2}, {1,2,1}, {1,7,1}} },       /* pieces=16 */
    { 462, 4, {{0,1,1}, {0,7,2}, {1,1,1}, {1,11,1}} },      /* pieces=20 */
    { 495, 3, {{0,3,1}, {0,5,2}, {1,11,0}} },                /* pieces=19 */
    { 504, 4, {{0,2,1}, {0,3,2}, {1,4,1}, {1,7,1}} },       /* pieces=16 */
    { 630, 4, {{0,1,1}, {0,3,2}, {1,5,1}, {1,7,1}} },       /* pieces=16 */
    { 720, 4, {{0,3,1}, {0,5,2}, {1,2,1}, {1,8,1}} },       /* pieces=18 */
    { 840, 4, {{0,2,1}, {0,5,2}, {1,4,1}, {1,7,1}} },       /* pieces=18 */
    { 990, 4, {{0,3,1}, {0,5,2}, {1,1,1}, {1,11,1}} },      /* pieces=20 */
    {1260, 5, {{0,3,1}, {0,5,2}, {1,2,0}, {1,2,1}, {1,7,1}} }, /* pieces=19 */

    /* Edge-heavy fallbacks: used when corner pieces are exhausted by earlier
     * registers.  Ordered by pieces-ascending so the cheapest edge option wins
     * when multiple entries share the same order. */
    {   2, 2, {{1,1,1}, {1,1,1}} },                            /* edge pieces=2  */
    {   3, 1, {{1,3,0}} },                                     /* edge pieces=3  */
    {   4, 2, {{1,2,1}, {1,2,1}} },                            /* edge pieces=4  */
    {   5, 1, {{1,5,0}} },                                     /* edge pieces=5  */
    {   6, 3, {{1,3,0}, {1,1,1}, {1,1,1}} },                  /* edge pieces=5  */
    {   7, 1, {{1,7,0}} },                                     /* edge pieces=7  */
    {   8, 2, {{1,4,1}, {1,2,1}} },                            /* edge pieces=6  */
    {   9, 1, {{1,9,0}} },                                     /* edge pieces=9  */
    {  10, 3, {{1,5,0}, {1,1,1}, {1,1,1}} },                  /* edge pieces=7  */
    {  11, 1, {{1,11,0}} },                                    /* edge pieces=11 */
    {  12, 3, {{1,3,0}, {1,2,1}, {1,2,1}} },                  /* edge pieces=7  */
    {  14, 3, {{1,7,0}, {1,1,1}, {1,1,1}} },                  /* edge pieces=9  */
    {  15, 2, {{1,5,0}, {1,3,0}} },                            /* edge pieces=8  */
    {  16, 2, {{1,8,1}, {1,2,1}} },                            /* edge pieces=10 */
    {  18, 3, {{1,9,0}, {1,1,1}, {1,1,1}} },                  /* edge pieces=11 */
    {  20, 3, {{1,5,0}, {1,2,1}, {1,2,1}} },                  /* edge pieces=9  */
    {  21, 2, {{1,7,0}, {1,3,0}} },                            /* edge pieces=10 */
    {  24, 3, {{1,3,0}, {1,4,1}, {1,2,1}} },                  /* edge pieces=9  */
    {  28, 3, {{1,7,0}, {1,2,1}, {1,2,1}} },                  /* edge pieces=11 */
    {  30, 4, {{1,5,0}, {1,3,0}, {1,1,1}, {1,1,1}} },        /* edge pieces=10 */
    {  35, 2, {{1,7,0}, {1,5,0}} },                            /* edge pieces=12 */
    {  42, 4, {{1,7,0}, {1,3,0}, {1,1,1}, {1,1,1}} },        /* edge pieces=12 */
    {  60, 4, {{1,5,0}, {1,3,0}, {1,2,1}, {1,2,1}} },        /* edge pieces=12 */
};

typedef struct {
    int      order;
    CycleSet cycles;
    char    *algorithm;
} RegCacheEntry;

static RegCacheEntry *g_regcache = NULL;
static int g_regcache_count = 0;
static int g_regcache_cap = 0;
static bool g_regcache_loaded = false;

#define REGCACHE_MAGIC   0x52474343u /* "RGCC", little-endian on disk */
#define REGCACHE_VERSION 1u
#define REGCACHE_MAX_ALG_LEN 4096u

static void regcache_push_owned(int order, CycleSet cycles, char *algorithm) {
    if (g_regcache_count == g_regcache_cap) {
        int new_cap = next_cap(g_regcache_cap);
        RegCacheEntry *new_entries = realloc(
            g_regcache, (size_t)new_cap * sizeof *new_entries);
        if (!new_entries)
            die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE, "OOM: regcache");
        g_regcache = new_entries;
        g_regcache_cap = new_cap;
    }

    g_regcache[g_regcache_count++] = (RegCacheEntry){
        .order = order,
        .cycles = cycles,
        .algorithm = algorithm,
    };
}

static bool regcache_read_u32(FILE *fp, uint32_t *out) {
    return fread(out, sizeof *out, 1, fp) == 1;
}

static void regcache_load(void) {
    if (g_regcache_loaded) return;
    g_regcache_loaded = true;

    FILE *fp = fopen(REGALLOC_CACHE_PATH, "rb");
    if (!fp) return;

    uint32_t magic = 0, version = 0, count = 0;
    if (!regcache_read_u32(fp, &magic) ||
        !regcache_read_u32(fp, &version) ||
        !regcache_read_u32(fp, &count) ||
        magic != REGCACHE_MAGIC ||
        version != REGCACHE_VERSION) {
        fclose(fp);
        return;
    }

    for (uint32_t i = 0; i < count; i++) {
        uint32_t order = 0, cycles = 0, alg_len = 0;
        if (!regcache_read_u32(fp, &order) ||
            !regcache_read_u32(fp, &cycles) ||
            !regcache_read_u32(fp, &alg_len) ||
            alg_len == 0 ||
            alg_len > REGCACHE_MAX_ALG_LEN) {
            break;
        }

        char *algorithm = malloc((size_t)alg_len + 1);
        if (!algorithm) die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE, "OOM: regcache_load");
        if (fread(algorithm, 1, alg_len, fp) != alg_len) {
            free(algorithm);
            break;
        }
        algorithm[alg_len] = '\0';
        regcache_push_owned((int)order, (CycleSet)cycles, algorithm);
    }

    fclose(fp);
}

static void regcache_save(void) {
    FILE *fp = fopen(REGALLOC_CACHE_PATH, "wb");
    if (!fp) return;

    uint32_t magic = REGCACHE_MAGIC;
    uint32_t version = REGCACHE_VERSION;
    uint32_t count = (uint32_t)g_regcache_count;
    if (fwrite(&magic, sizeof magic, 1, fp) != 1 ||
        fwrite(&version, sizeof version, 1, fp) != 1 ||
        fwrite(&count, sizeof count, 1, fp) != 1) {
        fclose(fp);
        return;
    }

    for (int i = 0; i < g_regcache_count; i++) {
        uint32_t order = (uint32_t)g_regcache[i].order;
        uint32_t cycles = (uint32_t)g_regcache[i].cycles;
        size_t len = strlen(g_regcache[i].algorithm);
        if (len == 0 || len > REGCACHE_MAX_ALG_LEN) continue;
        uint32_t alg_len = (uint32_t)len;
        if (fwrite(&order, sizeof order, 1, fp) != 1 ||
            fwrite(&cycles, sizeof cycles, 1, fp) != 1 ||
            fwrite(&alg_len, sizeof alg_len, 1, fp) != 1 ||
            fwrite(g_regcache[i].algorithm, 1, len, fp) != len) {
            break;
        }
    }

    fclose(fp);
}

static bool regcache_lookup(int order, CycleSet cycles, CycleSet forbidden,
                            Alg *out) {
    regcache_load();

    for (int i = 0; i < g_regcache_count; i++) {
        if (g_regcache[i].order != order || g_regcache[i].cycles != cycles)
            continue;

        Alg alg = {0};
        if (!alg_parse(g_regcache[i].algorithm, &alg)) continue;
        if (compute_order(&alg) == order &&
            cycleset_from_alg(&alg) == cycles &&
            cycleset_disjoint(cycles, forbidden)) {
            *out = alg;
            return true;
        }
        alg_free(&alg);
    }

    return false;
}

static void regcache_store(int order, CycleSet cycles, const Alg *alg) {
    regcache_load();

    for (int i = 0; i < g_regcache_count; i++)
        if (g_regcache[i].order == order && g_regcache[i].cycles == cycles)
            return;

    char *algorithm = alg_to_string(alg);
    if (!algorithm) return;
    regcache_push_owned(order, cycles, algorithm);
    regcache_save();
}

/* --- Register table --- */

/* Append an entry to the register table, doubling capacity as needed. */
static void regtable_push(RegTable *t, const RegEntry entry) {
    if (t->count == t->cap) {
        const int newcap = next_cap(t->cap);
        t->regs = realloc(t->regs, (size_t)newcap * sizeof(RegEntry));
        if (!t->regs) die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE, "OOM: regtable_push");
        t->cap = newcap;
    }
    t->regs[t->count++] = entry;
}

static int find_and_add_impl(RegTable *table, const CycleSet forbidden,
                             const int required_order, bool prefer_corners);

/* Initialise the table with R0 and an empty R1 placeholder.
 *
 * R1 is realized after variable coloring in regalloc_run, once the actual
 * free piece pool and maximum variable order are known. Pre-allocating R1
 * here would block variables from using pieces that R1 claims, potentially
 * forcing variables to escalate to higher orders than declared. */
void regalloc_init(RegTable *table) {
    *table = (RegTable){0};

    Alg r0 = {0};
    if (!alg_parse(R0_ALGORITHM, &r0))
        die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE,
            "regalloc_init: could not parse R0 algorithm \"%s\"", R0_ALGORITHM);

    const CycleSet cs = cycleset_from_alg(&r0);
    const int order = compute_order(&r0);
    char *alg_str = alg_to_string(&r0);
    alg_free(&r0);

    regtable_push(table, (RegEntry){
        .algorithm = alg_str,
        .order     = order,
        .cycles    = cs,
        .index     = 0,
    });
    table->r0_reserved = true;

    /* R1 placeholder: empty cycles so build_forbidden ignores it during
     * variable coloring. Realized by regalloc_run after all variables
     * are assigned. */
    regtable_push(table, (RegEntry){
        .algorithm = strdup(""),
        .order     = 0,
        .cycles    = CYCLESET_EMPTY,
        .index     = 1,
    });
}

/* Free all owned algorithm strings and the entry array. */
void regalloc_free(RegTable *table) {
    for (int i = 0; i < table->count; i++) free(table->regs[i].algorithm);
    free(table->regs);
    *table = (RegTable){0};
}

/* --- IDA* search ---
 * Pruning rules (cuts branching factor from 18 to ~13):
 *   1. Never repeat the same face.
 *   2. Opposite-face canonical order: U<D, L<R, F<B (face^1 gives the
 *      opposite; skip if opposite and prev > cur, e.g. no U after D).
 *
 * Leaf check uses the running CubeState directly rather than re-applying
 * the path: cycle set is non-empty iff the sequence is non-identity
 * (equivalent to ord > 1), so compute_order is not needed at leaves.
 */

/* Derive a CycleSet from a live cube state: any displaced facelet marks its piece. */
static CycleSet cycleset_from_state(const CubeState *s) {
    CycleSet cs = CYCLESET_EMPTY;
    for (int i = 0; i < FACELET_COUNT; i++)
        if (s->state[i] != (uint8_t)i)
            cs |= (1u << (unsigned)facelet_to_piece[i]);
    return cs;
}

/* True if this move should be skipped: same face repeated, or opposite-face pair out of canonical order. */
static bool should_prune(const int prev_face, const int cur_face) {
    if (prev_face < 0) return false;
    if (cur_face == prev_face) return true;
    if ((cur_face ^ 1) == prev_face && prev_face > cur_face) return true;
    return false;
}

/* Write the first `depth` moves of path into out (growing as needed). */
static void idas_emit_path(const Move *path, const int depth, Alg *out) {
    out->len = 0;
    for (int i = 0; i < depth; i++) {
        if (out->len == out->cap) {
            const int nc = next_cap(out->cap);
            out->m = realloc(out->m, (size_t)nc * sizeof(Move));
            if (!out->m) die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE, "OOM: idas_dfs");
            out->cap = nc;
        }
        out->m[out->len++] = path[i];
    }
}

/* DFS leg of IDA*: extend the path one move at a time; write the found sequence into out on success.
 *
 * A leaf is accepted only when its cycle set is non-empty, disjoint from
 * forbidden, and — when required_order > 0 — when the realised algorithm's order
 * is at least required_order. The order filter is what lets the iterative
 * deepening keep searching deeper for a high-order register instead of latching
 * onto the first (shortest, lowest-order) disjoint sequence it stumbles on. */
static bool idas_dfs(const CubeState cur, Move *path, const int depth, const int limit,
                     const int prev_face, const CycleSet forbidden,
                     const int required_order, Alg *out) {
    if (depth == limit) {
        const CycleSet cs = cycleset_from_state(&cur);
        if (cs == CYCLESET_EMPTY) return false;
        if (!cycleset_disjoint(cs, forbidden)) return false;
        idas_emit_path(path, depth, out);
        if (required_order > 0 && compute_order(out) < required_order) {
            out->len = 0;
            return false;
        }
        return true;
    }

    for (int mi = 0; mi < MOVE_COUNT; mi++) {
        const int face = (int)ALL_MOVES[mi].face;
        if (should_prune(prev_face, face)) continue;
        path[depth] = ALL_MOVES[mi];
        CubeState next = cur;
        cube_apply_move(&next, (Face)face, (int)ALL_MOVES[mi].q);
        if (idas_dfs(next, path, depth + 1, limit, face, forbidden, required_order, out))
            return true;
    }
    return false;
}

/* Iterative-deepening wrapper: fallback DFS after CCS candidates are exhausted.
 * required_order == 0 means "any disjoint algorithm"; a positive value keeps
 * deepening until a disjoint algorithm of at least that order is found. */
static void idas_find(const CycleSet forbidden, const int required_order, Alg *out) {
    CubeState id;
    cube_identity(&id);
    Move path[REGALLOC_IDA_MAX_DEPTH];

    for (int limit = 1; limit <= REGALLOC_IDA_MAX_DEPTH; limit++)
        if (idas_dfs(id, path, 0, limit, -1, forbidden, required_order, out)) return;

    die(EXIT_CODE_REGALLOC, STAGE_REGALLOC, NO_SITE,
        "register pressure too high: no disjoint cube algorithm of order >= %d found "
        "via CCS or IDA search depth %d",
        required_order, REGALLOC_IDA_MAX_DEPTH);
}

static bool piece_allowed(PieceLabel p, CycleSet forbidden) {
    return (forbidden & (CycleSet)(1u << (unsigned)p)) == 0;
}

static int regalloc_gcd(int a, int b) {
    if (a < 0) a = -a;
    if (b < 0) b = -b;
    while (b != 0) {
        int t = a % b;
        a = b;
        b = t;
    }
    return a;
}

static int candidate_cycle_order(const RegCycleCandidate *cy) {
    int period = (cy->orbit == 0) ? 3 : 2;
    int g = regalloc_gcd((int)cy->net_orientation, period);
    if (g == 0) g = period;
    return cy->length * (period / g);
}


/* Callback context for try_ccs_candidate: carries the expected order,
 * forbidden set, result slot, and a cap on Kociemba invocations. */
typedef struct {
    int      order;
    int      num_cycles;  /* used to build CCSRegister.abstract */
    CycleSet forbidden;
    Alg     *out;
    bool     found;
    int      kociemba_calls; /* counts actual solver invocations */
} TryCCSCtx;

/* Hard limit: stop after this many Kociemba calls per template.
 * Keeps compile time bounded when many piece combinations exist.
 * Since probe_candidates shows every template succeeds with the first
 * available assignment, this cap is rarely reached in practice. */
static bool try_ccs_cb(CCSCycle cycles[CCF_MAX_REGISTERS][CCF_MAX_CYCLES_PER_REG],
                       int num_regs, void *ctx_) {
    TryCCSCtx *ctx = ctx_;
    (void)num_regs; /* always 1 for single-register candidates */

    /* Build CCSRegister from cycles[0][*]. */
    CCSRegister reg = {0};
    reg.abstract.order      = ctx->order;
    reg.abstract.num_cycles = ctx->num_cycles;
    for (int c = 0; c < ctx->num_cycles; c++) {
        reg.abstract.cycles[c] = cycles[0][c].abstract;
        reg.cycles[c]          = cycles[0][c];
    }

    /* Expected CycleSet for this piece assignment. */
    CycleSet want = CYCLESET_EMPTY;
    for (int c = 0; c < ctx->num_cycles; c++)
        for (int j = 0; j < reg.cycles[c].abstract.length; j++)
            want |= (CycleSet)(1u << (unsigned)reg.cycles[c].pieces[j]);

    /* Cache hit: no Kociemba call needed. */
    if (regcache_lookup(ctx->order, want, ctx->forbidden, ctx->out)) {
        ctx->found = true;
        return false; /* stop enumeration */
    }

    ctx->kociemba_calls++;

    Alg alg = {0};
    if (!ccs_find_alg(&reg, &alg)) return true; /* keep trying */

    int      order = compute_order(&alg);
    CycleSet cs    = cycleset_from_alg(&alg);
    if (order == ctx->order && cs == want && cycleset_disjoint(cs, ctx->forbidden)) {
        regcache_store(order, cs, &alg);
        *ctx->out = alg;
        ctx->found = true;
        return false; /* stop enumeration */
    }

    alg_free(&alg);
    return true; /* keep trying */
}

/* Try to find an algorithm for the given template using the available pieces.
 * Delegates all piece selection (all C(n,k) combinations, not just contiguous
 * windows) and orientation distribution (all splits of net_orientation across
 * positions) to ccs_enumerate_assignments, which handles both exhaustively.
 * The forbidden CycleSet is passed directly so pieces claimed by other
 * registers are never selected. */
static bool try_ccs_candidate(const RegCandidate *candidate,
                              CycleSet forbidden, Alg *out) {
    /* Quick feasibility check before building the architecture. */
    int need_c = 0, need_e = 0;
    for (int i = 0; i < candidate->num_cycles; i++) {
        if (candidate->cycles[i].orbit == 0) need_c += candidate->cycles[i].length;
        else                                 need_e += candidate->cycles[i].length;
    }
    /* Count available pieces per orbit. */
    int nc = 0, ne = 0;
    for (int i = 0; i < (int)(sizeof CORNER_PIECES / sizeof CORNER_PIECES[0]); i++)
        if (piece_allowed(CORNER_PIECES[i], forbidden)) nc++;
    for (int i = 0; i < (int)(sizeof EDGE_PIECES / sizeof EDGE_PIECES[0]); i++)
        if (piece_allowed(EDGE_PIECES[i], forbidden)) ne++;
    if (need_c > nc || need_e > ne) return false;

    /* Build a single-register CCFArchitecture from the candidate. */
    CCFArchitecture arch = {0};
    arch.num_registers = 1;
    arch.registers[0].num_cycles = candidate->num_cycles;
    arch.registers[0].order      = candidate->order;
    for (int i = 0; i < candidate->num_cycles; i++) {
        arch.registers[0].cycles[i] = (CCFCycle){
            .orbit           = candidate->cycles[i].orbit,
            .length          = candidate->cycles[i].length,
            .net_orientation = candidate->cycles[i].net_orientation,
            .order           = candidate_cycle_order(&candidate->cycles[i]),
        };
    }

    TryCCSCtx ctx = {
        .order      = candidate->order,
        .num_cycles = candidate->num_cycles,
        .forbidden  = forbidden,
        .out        = out,
    };

    ccs_enumerate_assignments(&arch, forbidden, try_ccs_cb, &ctx);
    return ctx.found;
}

/* True when every cycle of the candidate lives in the corner orbit. Corner
 * registers are "dense": three orientations per piece means a 3- or 4-cycle of
 * corners reaches order 9 or 12 on just 3-4 pieces, where the same order on
 * edges would need a long cycle. Reserving such a register for the scratch slot
 * leaves the roomy 12-edge space free for ordinary variables. */
static bool candidate_is_corner_only(const RegCandidate *c) {
    for (int i = 0; i < c->num_cycles; i++)
        if (c->cycles[i].orbit != 0) return false;
    return true;
}

/* Prefer compact Kociemba-backed cycle templates before the old bounded blind
 * search. For constrained variables, try the requested order and then larger
 * known templates incrementally. When prefer_corners is set, corner-only
 * templates are tried first so the chosen register is dense (see
 * candidate_is_corner_only). */
static bool ccs_find_small_register(CycleSet forbidden, int required_order,
                                    bool prefer_corners, Alg *out) {
    int n = (int)(sizeof REG_CANDIDATES / sizeof REG_CANDIDATES[0]);

    if (required_order == 0 && !prefer_corners) {
        for (int i = 0; i < n; i++) {
            if (REG_CANDIDATES[i].order != 3) continue;
            if (try_ccs_candidate(&REG_CANDIDATES[i], forbidden, out))
                return true;
        }
    }

    if (prefer_corners) {
        for (int i = 0; i < n; i++) {
            if (REG_CANDIDATES[i].order < required_order) continue;
            if (!candidate_is_corner_only(&REG_CANDIDATES[i])) continue;
            if (try_ccs_candidate(&REG_CANDIDATES[i], forbidden, out))
                return true;
        }
    }

    for (int i = 0; i < n; i++) {
        if (REG_CANDIDATES[i].order < required_order) continue;
        if (try_ccs_candidate(&REG_CANDIDATES[i], forbidden, out))
            return true;
    }

    return false;
}

/* Shared implementation: find a disjoint algorithm, append it, return its index.
 * prefer_corners biases the search toward dense corner registers, used for the
 * reserved scratch register so variables keep the edge space. */
static int find_and_add_impl(RegTable *table, const CycleSet forbidden,
                             const int required_order, bool prefer_corners) {
    Alg alg = {0};
    if (!ccs_find_small_register(forbidden, required_order, prefer_corners, &alg)) {
        idas_find(forbidden, required_order, &alg);
    }

    const int order   = compute_order(&alg);
    if (required_order > 0 && order < required_order) {
        alg_free(&alg);
        die(EXIT_CODE_REGALLOC, STAGE_REGALLOC, NO_SITE,
            "no disjoint algorithm with order >= %d found "
            "(CCS tried known templates up to order 1260; "
            "IDA fallback depth %d)", required_order, REGALLOC_IDA_MAX_DEPTH);
    }

    const int new_idx = table->count;
    char *alg_str     = alg_to_string(&alg);
    const CycleSet cs = cycleset_from_alg(&alg);
    alg_free(&alg);

    regtable_push(table, (RegEntry){
        .algorithm = alg_str,
        .order     = order,
        .cycles    = cs,
        .index     = new_idx,
    });
    return new_idx;
}

/* Find a new algorithm disjoint from forbidden, append it to the table, and
 * return its index. Compact CCS/Kociemba templates are preferred; bounded IDA*
 * remains as a fallback, mainly for non-3 order requests. */
int regalloc_find_and_add(RegTable *table, const CycleSet forbidden,
                          const int required_order) {
    return find_and_add_impl(table, forbidden, required_order, false);
}

/* --- Graph colouring --- */

/* Sort IGNode pointers: highest degree first, alphabetical on ties. */
static int cmp_node_degree_desc(const void *ap, const void *bp) {
    const IGNode *a = *(const IGNode *const *)ap;
    const IGNode *b = *(const IGNode *const *)bp;
    const int da = __builtin_popcountll((unsigned long long)a->neighbours);
    const int db = __builtin_popcountll((unsigned long long)b->neighbours);
    if (da != db) return db - da;
    return strcmp(a->name, b->name);
}

/* Build forbidden CycleSet: reserved registers plus every coloured neighbour's cycles. */
static CycleSet build_forbidden(const RegTable *table, const IGNode *node,
                                const int *coloring) {
    CycleSet forbidden = table->r0_reserved ? table->regs[0].cycles : CYCLESET_EMPTY;
    if (table->count > 1) {
        forbidden |= table->regs[1].cycles;
    }
    for (uint64_t bits = (uint64_t)node->neighbours; bits; bits &= bits - 1) {
        const int j = __builtin_ctzll(bits);
        if (coloring[j] >= 0)
            forbidden |= table->regs[coloring[j]].cycles;
    }
    return forbidden;
}

/* First usable register whose cycles/order fit, or -1. R1 is always temp-only. */
static int find_existing_reg(const RegTable *table, const CycleSet forbidden,
                             const int required_order) {
    for (int ri = 0; ri < table->count; ri++) {
        if (ri == 1) continue;
        if (ri == 0 && table->r0_reserved) continue;
        if (required_order > 0 && table->regs[ri].order < required_order)
            continue;
        if (cycleset_disjoint(table->regs[ri].cycles, forbidden))
            return ri;
    }
    return -1;
}

/* Verify: every assigned register is disjoint from reserved registers and from every
 * interfering neighbour. die(EXIT_CODE_INTERNAL) on violation. */
static void check_invariants(const RegTable *table, const InterferenceGraph *ig,
                              const int *coloring) {
    for (int i = 0; i < ig->count; i++) {
        const int a_idx = ig->nodes[i].var_index;
        const int ra    = coloring[a_idx];
        if (ra < 0)
            die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE,
                "regalloc invariant: \"%s\" was not assigned a register",
                ig->nodes[i].name);
        if (table->r0_reserved &&
            !cycleset_disjoint(table->regs[ra].cycles, table->regs[0].cycles))
            die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE,
                "regalloc invariant: \"%s\" assigned R%d overlaps R0",
                ig->nodes[i].name, ra);
        if (ra == 1 || !cycleset_disjoint(table->regs[ra].cycles, table->regs[1].cycles))
            die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE,
                "regalloc invariant: \"%s\" assigned R%d overlaps reserved temp R1",
                ig->nodes[i].name, ra);
        for (uint64_t bits = (uint64_t)ig->nodes[i].neighbours; bits; bits &= bits - 1) {
            const int b_idx = __builtin_ctzll(bits);
            const int rb    = coloring[b_idx];
            if (rb < 0) continue;
            if (!cycleset_disjoint(table->regs[ra].cycles, table->regs[rb].cycles))
                die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE,
                    "regalloc invariant: interfering variables share overlapping registers R%d and R%d", ra, rb);
        }
    }
}

/* Realize the R1 scratch register from the pieces that remain after R0 and
 * all variables are accounted for. Called after variable coloring so that R1
 * never competes with variables for pieces. */
static void realize_temp(RegTable *table, const InterferenceGraph *ig,
                         const int *coloring) {
    int max_var_order = 0;
    CycleSet all_var_cycles = CYCLESET_EMPTY;
    for (int i = 0; i < ig->count; i++) {
        int ri = coloring[ig->nodes[i].var_index];
        if (table->regs[ri].order > max_var_order)
            max_var_order = table->regs[ri].order;
        all_var_cycles |= table->regs[ri].cycles;
    }
    /* R0 is pre-assigned outside the IG but can appear as an operand in
     * add/sub/compare, all of which route through the temp. */
    if (table->r0_reserved && table->regs[0].order > max_var_order)
        max_var_order = table->regs[0].order;

    CycleSet forbidden = all_var_cycles;
    if (table->r0_reserved) forbidden |= table->regs[0].cycles;

    Alg temp = {0};
    if (max_var_order == 0) {
        if (!ccs_find_small_register(forbidden, 3, false, &temp))
            idas_find(forbidden, 3, &temp);
    } else {
        if (!ccs_find_small_register(forbidden, max_var_order, true, &temp) &&
            !ccs_find_small_register(forbidden, max_var_order, false, &temp)) {
            die(EXIT_CODE_REGALLOC, STAGE_REGALLOC, NO_SITE,
                "no register with order >= %d available for the scratch slot; "
                "program uses too many cube pieces", max_var_order);
        }
    }

    free(table->regs[1].algorithm);
    table->regs[1].algorithm = alg_to_string(&temp);
    table->regs[1].order     = compute_order(&temp);
    table->regs[1].cycles    = cycleset_from_alg(&temp);
    alg_free(&temp);
}

/* Colour every IG node with a disjoint register; return colouring[var_index] = RegTable index. */
int *regalloc_run(RegTable *table, const InterferenceGraph *ig) {
    const int env_count = ig->env->count;

    int *coloring = malloc((size_t)env_count * sizeof(int));
    if (!coloring) die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE, "OOM: regalloc_run");
    for (int i = 0; i < env_count; i++) coloring[i] = -1;
    coloring[0] = 0; /* R0 pre-assigned */

    /* Sort nodes by degree desc, alphabetical tiebreak. */
    IGNode **sorted = malloc((size_t)ig->count * sizeof(IGNode *));
    if (!sorted) die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE, "OOM: regalloc_run sort");
    for (int i = 0; i < ig->count; i++) sorted[i] = &ig->nodes[i];
    qsort(sorted, (size_t)ig->count, sizeof(IGNode *), cmp_node_degree_desc);

    for (int i = 0; i < ig->count; i++) {
        const IGNode *node       = sorted[i];
        const int required       = node->required_order;
        const CycleSet forbidden = build_forbidden(table, node, coloring);
        int ri = find_existing_reg(table, forbidden, required);
        if (ri < 0) ri = regalloc_find_and_add(table, forbidden, required);
        coloring[node->var_index] = ri;
    }

    free(sorted);
    realize_temp(table, ig, coloring);
    check_invariants(table, ig, coloring);
    return coloring;
}

/* --- Dump --- */

/* Sort IGNode pointers alphabetically by name. */
static int cmp_node_name_asc(const void *ap, const void *bp) {
    const IGNode *a = *(const IGNode *const *)ap;
    const IGNode *b = *(const IGNode *const *)bp;
    return strcmp(a->name, b->name);
}

/* Print a CycleSet as a brace-enclosed comma-separated piece list, e.g. {UF,UFR,UR}. */
static void cycleset_dump(const CycleSet cs, FILE *out) {
    fputc('{', out);
    bool first = true;
    for (int p = 0; p < PC_COUNT; p++) {
        if (cs & (1u << (unsigned)p)) {
            if (!first) fputc(',', out);
            fputs(piece_to_string(p), out);
            first = false;
        }
    }
    fputc('}', out);
}

/* Print one "var -> Ri  alg=... K=n C={...}" line per variable, sorted by name. */
void regalloc_dump(const RegTable *table, const InterferenceGraph *ig,
                   const int *coloring, FILE *out) {
    if (table->r0_reserved) {
        fprintf(out, "%s -> R0  alg=\"%s\" K=%d C=",
                R0_SYNTHETIC_VARIABLE,
                table->regs[0].algorithm,
                table->regs[0].order);
        cycleset_dump(table->regs[0].cycles, out);
        fputc('\n', out);
    }

    IGNode **sorted = malloc((size_t)ig->count * sizeof(IGNode *));
    if (!sorted) die(EXIT_CODE_INTERNAL, STAGE_INTERNAL, NO_SITE, "OOM: regalloc_dump");
    for (int i = 0; i < ig->count; i++) sorted[i] = &ig->nodes[i];
    qsort(sorted, (size_t)ig->count, sizeof(IGNode *), cmp_node_name_asc);

    for (int i = 0; i < ig->count; i++) {
        const int ri = coloring[sorted[i]->var_index];
        fprintf(out, "%s -> R%d  alg=\"%s\" K=%d C=",
                sorted[i]->name, ri,
                table->regs[ri].algorithm,
                table->regs[ri].order);
        cycleset_dump(table->regs[ri].cycles, out);
        fputc('\n', out);
    }

    free(sorted);
}
